// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using centermuebles_tesis.modelos;

#nullable disable

namespace centermuebles_tesis.Migrations
{
    [DbContext(typeof(CentermueblesContext))]
    [Migration("20251109234935_AgregarCodigoPostalUsuario")]
    partial class AgregarCodigoPostalUsuario
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("centermuebles_tesis.modelos.CarritoCompras", b =>
                {
                    b.Property<int>("IdCarrito")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCarrito"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaAgregado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("IdProducto")
                        .HasColumnType("int");

                    b.Property<string>("IdSesion")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<int?>("IdUsuario")
                        .HasColumnType("int");

                    b.HasKey("IdCarrito");

                    b.HasIndex("IdProducto");

                    b.HasIndex("IdUsuario");

                    b.ToTable("CarritoCompras");
                });

            modelBuilder.Entity("centermuebles_tesis.modelos.Categorias", b =>
                {
                    b.Property<int>("IdCategoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCategoria"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("IdCategoria");

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("centermuebles_tesis.modelos.DetalleVentas", b =>
                {
                    b.Property<int>("IdDetalle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDetalle"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int>("IdProducto")
                        .HasColumnType("int");

                    b.Property<int>("IdVenta")
                        .HasColumnType("int");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal>("SubTotal")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("IdDetalle");

                    b.HasIndex("IdProducto");

                    b.HasIndex("IdVenta");

                    b.ToTable("DetalleVentas");
                });

            modelBuilder.Entity("centermuebles_tesis.modelos.ImagenProducto", b =>
                {
                    b.Property<int>("IdImagen")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdImagen"));

                    b.Property<int>("IdProducto")
                        .HasColumnType("int");

                    b.Property<bool>("ImagenPrincipal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("NombreArchivo")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("Orden")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("RutaImagen")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.HasKey("IdImagen");

                    b.HasIndex("IdProducto");

                    b.ToTable("ImagenesProducto");
                });

            modelBuilder.Entity("centermuebles_tesis.modelos.Producto", b =>
                {
                    b.Property<int>("IdProducto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProducto"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("text");

                    b.Property<int>("IdSubcategoria")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("RutaImagen")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("IdProducto");

                    b.HasIndex("IdSubcategoria");

                    b.ToTable("Productos");
                });

            modelBuilder.Entity("centermuebles_tesis.modelos.Subcategorias", b =>
                {
                    b.Property<int>("IdSubcategoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSubcategoria"));

                    b.Property<int>("IdCategoria")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("IdSubcategoria");

                    b.HasIndex("IdCategoria");

                    b.ToTable("Subcategorias");
                });

            modelBuilder.Entity("centermuebles_tesis.modelos.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<string>("CodigoPostal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Contraseña")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Direccion")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasDefaultValue("Cliente");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("IdUsuario");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("NombreUsuario")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("centermuebles_tesis.modelos.Venta", b =>
                {
                    b.Property<int>("IdVenta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdVenta"));

                    b.Property<string>("EstadoVenta")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("Completada");

                    b.Property<DateTime?>("FechaVenta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<string>("MetodoPago")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("ProductoIdProducto")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalVenta")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("IdVenta");

                    b.HasIndex("IdUsuario");

                    b.HasIndex("ProductoIdProducto");

                    b.ToTable("Ventas");
                });

            modelBuilder.Entity("centermuebles_tesis.modelos.CarritoCompras", b =>
                {
                    b.HasOne("centermuebles_tesis.modelos.Producto", "IdProductoNavigation")
                        .WithMany("CarritoCompras")
                        .HasForeignKey("IdProducto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_CarritoCompras_Productos");

                    b.HasOne("centermuebles_tesis.modelos.Usuario", "IdUsuarioNavigation")
                        .WithMany("CarritoCompras")
                        .HasForeignKey("IdUsuario")
                        .HasConstraintName("FK_CarritoCompras_Usuarios");

                    b.Navigation("IdProductoNavigation");

                    b.Navigation("IdUsuarioNavigation");
                });

            modelBuilder.Entity("centermuebles_tesis.modelos.DetalleVentas", b =>
                {
                    b.HasOne("centermuebles_tesis.modelos.Producto", "IdProductoNavigation")
                        .WithMany("DetalleVentas")
                        .HasForeignKey("IdProducto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_DetalleVentas_Productos");

                    b.HasOne("centermuebles_tesis.modelos.Venta", "IdVentaNavigation")
                        .WithMany("DetalleVentas")
                        .HasForeignKey("IdVenta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_DetalleVentas_Ventas");

                    b.Navigation("IdProductoNavigation");

                    b.Navigation("IdVentaNavigation");
                });

            modelBuilder.Entity("centermuebles_tesis.modelos.ImagenProducto", b =>
                {
                    b.HasOne("centermuebles_tesis.modelos.Producto", "Producto")
                        .WithMany("ImagenesProducto")
                        .HasForeignKey("IdProducto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ImagenesProducto_Productos");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("centermuebles_tesis.modelos.Producto", b =>
                {
                    b.HasOne("centermuebles_tesis.modelos.Subcategorias", "IdSubcategoriaNavigation")
                        .WithMany("Productos")
                        .HasForeignKey("IdSubcategoria")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Productos_Subcategorias");

                    b.Navigation("IdSubcategoriaNavigation");
                });

            modelBuilder.Entity("centermuebles_tesis.modelos.Subcategorias", b =>
                {
                    b.HasOne("centermuebles_tesis.modelos.Categorias", "IdCategoriaNavigation")
                        .WithMany("Subcategorias")
                        .HasForeignKey("IdCategoria")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Subcategorias_Categorias");

                    b.Navigation("IdCategoriaNavigation");
                });

            modelBuilder.Entity("centermuebles_tesis.modelos.Venta", b =>
                {
                    b.HasOne("centermuebles_tesis.modelos.Usuario", "IdUsuarioNavigation")
                        .WithMany("Ventas")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Ventas_Usuarios");

                    b.HasOne("centermuebles_tesis.modelos.Producto", null)
                        .WithMany("Ventas")
                        .HasForeignKey("ProductoIdProducto");

                    b.Navigation("IdUsuarioNavigation");
                });

            modelBuilder.Entity("centermuebles_tesis.modelos.Categorias", b =>
                {
                    b.Navigation("Subcategorias");
                });

            modelBuilder.Entity("centermuebles_tesis.modelos.Producto", b =>
                {
                    b.Navigation("CarritoCompras");

                    b.Navigation("DetalleVentas");

                    b.Navigation("ImagenesProducto");

                    b.Navigation("Ventas");
                });

            modelBuilder.Entity("centermuebles_tesis.modelos.Subcategorias", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("centermuebles_tesis.modelos.Usuario", b =>
                {
                    b.Navigation("CarritoCompras");

                    b.Navigation("Ventas");
                });

            modelBuilder.Entity("centermuebles_tesis.modelos.Venta", b =>
                {
                    b.Navigation("DetalleVentas");
                });
#pragma warning restore 612, 618
        }
    }
}
